import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header";
import "./globals.css";
import buildClient from "./lib/build-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await (await buildClient()).get("/api/users/currentuser");

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={data.currentUser} />
        {children}
      </body>
    </html>
  );
}
